const sneaks_data = [
  {
    asin: "B00770CBUS",
    product_title: "Nike Men&#x27;s Killshot 2",
    product_price: "$90.00",
    product_original_price: "$114.95",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: "2121",
    product_url: "https://www.amazon.com/dp/B00770CBUS",
    product_photo:
      "https://m.media-amazon.com/images/I/71bEY0bfGTL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: "null",
    product_minimum_offer_price: "$90.00",
    is_best_seller: "false",
    is_prime: "true",
    climate_pledge_friendly: "false",
  },
  {
    asin: "B07ZKYJBBJ",
    product_title: "Nike Killshot 2 Leather (Sail/Oil Grey-Gum Yellow 7.5)",
    product_price: "$105.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B07ZKYJBBJ",
    product_photo:
      "https://m.media-amazon.com/images/I/61CIH5-Nb1L._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$105.00",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },

  {
    asin: "B08L696FCD",
    product_title: "Nike Men&#x27;s Training Gymnastics Shoe",
    product_price: "$50.04",
    product_original_price: "$56.54",
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 30,
    product_url: "https://www.amazon.com/dp/B08L696FCD",
    product_photo:
      "https://m.media-amazon.com/images/I/810EmX8jO2L._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$50.04",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },

  {
    asin: "B08TR7Y16H",
    product_title: "Nike Men&#x27;s Running Shoes Sneaker, 8.5 US",
    product_price: "$82.00",
    product_original_price: "$102.35",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 10463,
    product_url: "https://www.amazon.com/dp/B08TR7Y16H",
    product_photo:
      "https://m.media-amazon.com/images/I/61jp8XJDAHL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$82.00",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },

  {
    asin: "B08C36MGPJ",
    product_title:
      "Nike Nyjah Free 2 Sneakers Summit White/Pink Blast/Pink Blast/Racer Blue",
    product_price: "$99.99",
    product_original_price: "$115.00",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 45,
    product_url: "https://www.amazon.com/dp/B08C36MGPJ",
    product_photo:
      "https://m.media-amazon.com/images/I/61drjdp7EaL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$99.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: "false",
  },
  {
    asin: "B0BCZN2MYG",
    product_title:
      "Nike Mens Blazer Low 77 Jumbo DN2158 101 White Black Sail - Size",
    product_price: "$132.05",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 54,
    product_url: "https://www.amazon.com/dp/B0BCZN2MYG",
    product_photo:
      "https://m.media-amazon.com/images/I/61unO+dHwpL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$132.05",
    is_best_seller: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B07P8BBYBQ",
    product_title: "NIKE Men&#x27;s Track &amp; Field Shoes",
    product_price: "$109.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 14070,
    product_url: "https://www.amazon.com/dp/B07P8BBYBQ",
    product_photo:
      "https://m.media-amazon.com/images/I/617mry-n3dL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$109.00",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B071R4VP6F",
    product_title: "Reebok Men&#x27;s Club C 85 Vintage Sneaker",
    product_price: "$74.95",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 7931,
    product_url: "https://www.amazon.com/dp/B071R4VP6F",
    product_photo:
      "https://m.media-amazon.com/images/I/71nYPv9XvPL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: "null",
    product_minimum_offer_price: "$74.95",
    is_best_seller: "false",
    is_prime: "true",
    climate_pledge_friendly: "false",
  },
  {
    asin: "B09NC3V7G9",
    product_title: "Nike Mens Space Hippie 01 DJ3056 003 Melon Tint - Size",
    product_price: "$77.99",
    product_original_price: "null",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 36,
    product_url: "https://www.amazon.com/dp/B09NC3V7G9",
    product_photo:
      "https://m.media-amazon.com/images/I/71lp5YWAlaL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: "null",
    product_minimum_offer_price: "$77.99",
    is_best_seller: "false",
    is_prime: "true",
    climate_pledge_friendly: "false",
  },

  {
    asin: "B097S4NBRH",
    product_title: "NIKE Women&#x27;s Gymnastics Shoes Trainers",
    product_price: "$72.81",
    product_original_price: "$78.23",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 1002,
    product_url: "https://www.amazon.com/dp/B097S4NBRH",
    product_photo:
      "https://m.media-amazon.com/images/I/81689hV-QKL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$72.81",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B07QSYZL1P",
    product_title: "Nike Basketball Shoe",
    product_price: "$105.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 2851,
    product_url: "https://www.amazon.com/dp/B07QSYZL1P",
    product_photo:
      "https://m.media-amazon.com/images/I/71aw2Z+2WML._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$105.00",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B07NVTJD52",
    product_title: "Nike Sb Alleyoop Mens Trainers Cj0882 Sneakers Shoes",
    product_price: "$85.09",
    product_original_price: "$106.89",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: "55",
    product_url: "https://www.amazon.com/dp/B07NVTJD52",
    product_photo:
      "https://m.media-amazon.com/images/I/71-cFcXa0bL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: "null",
    product_minimum_offer_price: "$85.09",
    is_best_seller: "false",
    is_prime: "true",
    climate_pledge_friendly: "false",
  },
  {
    asin: "B0BXM2F4FW",
    product_title: "Nike GTS 97 Black/White Men&#x27;s Retro Shoes",
    product_price: "$59.98",
    product_original_price: "null",
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: "202",
    product_url: "https://www.amazon.com/dp/B0BXM2F4FW",
    product_photo:
      "https://m.media-amazon.com/images/I/51JARmzkNAL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: "null",
    product_minimum_offer_price: "$59.98",
    is_best_seller: "false",
    is_prime: "true",
    climate_pledge_friendly: "false",
  },
];
