const costumes_data = [
  {
    asin: "B089VLF9KT",
    product_title:
      "Halloween Spider Costume for Dog Cat, Halloween Pet Costume Halloween Decorations, Spider Decor Halloween Party Supply, Spider Cosplay Costumes with Adjustable Velcro for Small Medium Dogs and Cats",
    product_price: "$8.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.7",
    product_num_ratings: 497,
    product_url: "https://www.amazon.com/dp/B089VLF9KT",
    product_photo:
      "https://m.media-amazon.com/images/I/710SoDYjILS._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$8.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09V753TRH",
    product_title:
      "5 Pieces Pet Cat Halloween Costume Small Dog Vampire Cloak Bat Pumpkin Witch Hat with Adjustable Strap Skeleton Dog Bib Collar with Bells for Cat Halloween Bloody Zombie Party (Simple Style)",
    product_price: "$14.99",
    product_original_price: "$15.99",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 25,
    product_url: "https://www.amazon.com/dp/B09V753TRH",
    product_photo:
      "https://m.media-amazon.com/images/I/71kYrVRmcUL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$14.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09499WPND",
    product_title:
      "T2Y Cowboy Rider Dog Costume - Halloween Dog Costumes for Small Dogs or Cats, Dogs Clothes Knight Style with Doll and Hat for Halloween Day Pet Costume(Small)",
    product_price: "$12.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 371,
    product_url: "https://www.amazon.com/dp/B09499WPND",
    product_photo:
      "https://m.media-amazon.com/images/I/41EakiB0FWL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$12.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0CB2C7RP9",
    product_title:
      "Vellibring Halloween Pet Cape Costume Cat Vampire Cloak Cat Wizard Outfit Pet Witch Cosplay Apparel Halloween Pet Cloak Party Costumes for Small Medium Dogs Cats Supplies",
    product_price: "$9.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: 3,
    product_url: "https://www.amazon.com/dp/B0CB2C7RP9",
    product_photo:
      "https://m.media-amazon.com/images/I/71+ldmQU+YL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$9.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B08BJMD2GR",
    product_title:
      "Dog Cat Spider Costume for Halloween Party Decoration, Halloween Cosplay Costumes for Small Dogs and Cat, Puppy Cat Dress Up Accessories Black",
    product_price: "$7.99",
    product_original_price: "$9.99",
    currency: "USD",
    product_star_rating: "3.6",
    product_num_ratings: 633,
    product_url: "https://www.amazon.com/dp/B08BJMD2GR",
    product_photo:
      "https://m.media-amazon.com/images/I/61PPCI3J62L._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$7.99",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B06XVY9G39",
    product_title:
      "NACOCO Cowboy Dog Costume with Hat Dog Clothes Halloween Costumes for Cat and Small Dog (Medium) Blue",
    product_price: "$13.49",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 1331,
    product_url: "https://www.amazon.com/dp/B06XVY9G39",
    product_photo:
      "https://m.media-amazon.com/images/I/51itKrppI2L._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$13.49",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0B6F5VMX2",
    product_title:
      "Dog Cape Costume - Pet Halloween Costumes Cat Vampire Cloak, Dog Witch Clothes for Small Medium Dogs Cats Puppy, Funny Dog Cosplay Dress Wizard Outfit, Dog Mantle Apparel for Halloween Party",
    product_price: "$12.99",
    product_original_price: "$19.99",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 106,
    product_url: "https://www.amazon.com/dp/B0B6F5VMX2",
    product_photo:
      "https://m.media-amazon.com/images/I/71DSqmlWmTL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$12.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09C66V1SZ",
    product_title:
      "Dxhycc Halloween Pet Costume Cat Wizard Costume Funny Wizard Cat Clothes Cloak and Wizard Hat for Small Dogs Cats Outfits",
    product_price: "$9.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 145,
    product_url: "https://www.amazon.com/dp/B09C66V1SZ",
    product_photo:
      "https://m.media-amazon.com/images/I/71i4gLCjzZL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$9.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09XXHQ7VP",
    product_title:
      "YUJUN Cat Halloween Costume Pets Bat Wing with Pumpkin Shaped Jingle Bells Accessory for Puppy Kitten Halloween Party Costume Supplies",
    product_price: "$6.29",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4",
    product_num_ratings: 100,
    product_url: "https://www.amazon.com/dp/B09XXHQ7VP",
    product_photo:
      "https://m.media-amazon.com/images/I/61EJ00YWeCL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$6.29",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0711H3RB6",
    product_title:
      "Mikayoo Pet Dog Cat Halloween Costumes,The Cowboy for Party Christmas Special Events Costume,West Cowboy Uniform with Hat,Funny Pet Cowboy Outfit Clothing for Dog cat(XS)",
    product_price: "$11.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 1127,
    product_url: "https://www.amazon.com/dp/B0711H3RB6",
    product_photo:
      "https://m.media-amazon.com/images/I/617litpPQoL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$11.98",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0B56C66J2",
    product_title:
      "ITESSY Cat Halloween Costumes- Black Lion Mane Wig Pet Costumes Hat for Halloween Christmas Dress Up Accessories Decoration for Kitten Cats,Size M",
    product_price: "$9.23",
    product_original_price: "$10.99",
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 98,
    product_url: "https://www.amazon.com/dp/B0B56C66J2",
    product_photo:
      "https://m.media-amazon.com/images/I/71qG2vz53qL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$9.23",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B07GFND8ZC",
    product_title:
      "Pet Cat Bat Wings for Halloween Party Decoration, Puppy Collar Leads Cosplay Bat Costume,Cute Puppy Cat Dress Up Accessories",
    product_price: "$5.59",
    product_original_price: "$12.99",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 6867,
    product_url: "https://www.amazon.com/dp/B07GFND8ZC",
    product_photo:
      "https://m.media-amazon.com/images/I/51kh1vgB9aL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$5.59",
    is_best_seller: true,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0BBZVRDTH",
    product_title:
      "Finevalue Cat Dog Noble Halloween Cloak Cool Vampire Suit Cosplay Dress Outfit Small Medium Cat Dog Puppy Devil Costume (JZZ008-1)",
    product_price: "$14.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 34,
    product_url: ",https://www.amazon.com/dp/B0BBZVRDTH",
    product_photo:
      "https://m.media-amazon.com/images/I/61PE9ImtdkL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$14.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B074WP1RT3",
    product_title:
      "ANIAC Pet Pumpkin Costume Cat Halloween Hat Cloak Sets Puppy Poncho Dog Halloween Cosplay for Kitty Small Medium Sized Dog",
    product_price: "$13.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 220,
    product_url: "https://www.amazon.com/dp/B074WP1RT3",
    product_photo:
      "https://m.media-amazon.com/images/I/51kou410CqL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$13.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
];
