const sneaks_data = [
  {
    asin: "B09KDLZDKW",
    product_title: "Nike Air Huarache, Men&#x27;s Running Shoes",
    product_price: "$99.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: "12",
    product_url: "https://www.amazon.com/dp/B09KDLZDKW",
    product_photo:
      "https://m.media-amazon.com/images/I/51uBjPAKjeL Background Removed._AC_SR525,789_QL65_ 2.png",
    product_num_offers: null,
    product_minimum_offer_price: "$99.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0B5B5DFHB",
    product_title: "Nike Air Huarache Se Womens",
    product_price: "$86.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4",
    product_num_ratings: "5",
    product_url: "https://www.amazon.com/dp/B0B5B5DFHB",
    product_photo:
      "https://m.media-amazon.com/images/I/6193wZ0x-JL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$86.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B099Q1Z1SR",
    product_title: "Nike Unisex-Child Free Rn (Big Kid) Running Shoes, 6.5 US",
    product_price: "$73.90",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: "5220",
    product_url: "https://www.amazon.com/dp/B099Q1Z1SR",
    product_photo:
      "https://m.media-amazon.com/images/I/41uiBby-JqL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$73.90",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09J3J72Q3",
    product_title:
      "Nike Men&#x27;s Air Huarache Fashion Sneakers, Black/Black, 7.5",
    product_price: "$89.99",
    product_original_price: "$109.96",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: "8",
    product_url: "https://www.amazon.com/dp/B09J3J72Q3",
    product_photo:
      "https://m.media-amazon.com/images/I/51+z7E8P3hL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$89.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0BHXXN5G7",
    product_title:
      "Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Tan 4150",
    product_price: "$49.49",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: "70",
    product_url: "https://www.amazon.com/dp/B0BHXXN5G7",
    product_photo:
      "https://m.media-amazon.com/images/I/612maGs6i9L._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$49.49",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B06Y22QF81",
    product_title: "Deer Stags Men&#x27;s Huarache Sandal",
    product_price: "$54.99",
    product_original_price: "$85.00",
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: "2649",
    product_url: "https://www.amazon.com/dp/B06Y22QF81",
    product_photo:
      "https://m.media-amazon.com/images/I/71sDktg4sjL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$54.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0BZ3YNYSY",
    product_title:
      "Mexico en la Piel Leather Lace Up Huarache Sandals for Woman. Chiselled Flowers",
    product_price: "$49.59",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.7",
    product_num_ratings: "17",
    product_url: "https://www.amazon.com/dp/B0BZ3YNYSY",
    product_photo:
      "https://m.media-amazon.com/images/I/51GOvCheZDL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$49.59",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0BVF1SNSP",
    product_title:
      "Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Shedron 911 Ankle Strap",
    product_price: "$49.49",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: "28",
    product_url: "https://www.amazon.com/dp/B0BVF1SNSP",
    product_photo:
      "https://m.media-amazon.com/images/I/61H9df1FC7L Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$49.49",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0BZCJ3R31",
    product_title:
      "Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Shedron Erica",
    product_price: "$49.49",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: "14",
    product_url: "https://www.amazon.com/dp/B0BZCJ3R31",
    product_photo:
      "https://m.media-amazon.com/images/I/61yqN2pLFCL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$49.49",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B08FXT1TGW",
    product_title:
      "Generic The Western Shops Mens Leather Sandals Mens Mexican Huarache Sandal",
    product_price: "$39.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4",
    product_num_ratings: "143",
    product_url: "https://www.amazon.com/dp/B08FXT1TGW",
    product_photo:
      "https://m.media-amazon.com/images/I/71RDLRP0UOL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$39.99",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09H688BWP",
    product_title:
      "Generic Western Shops Womens Leather Mexican Huarache Sandal, Womens Huarache Leather Wedge Sandal",
    product_price: "$48.95",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: "154",
    product_url: "https://www.amazon.com/dp/B09H688BWP",
    product_photo:
      "https://m.media-amazon.com/images/I/71LOgkJEWZL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$48.95",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B081LLZWCY",
    product_title:
      "Sunsteps Venetian Women&#x27;s Hand Woven Leather Huarache Sandal for All-Day Comfort",
    product_price: "$44.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: "394",
    product_url: "https://www.amazon.com/dp/B081LLZWCY",
    product_photo:
      "https://m.media-amazon.com/images/I/612Kw6xCRAL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$44.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0BVV1BX6R",
    product_title:
      "Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Tan 3050 Ankle Strap",
    product_price: "$49.49",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: "4",
    product_url: "https://www.amazon.com/dp/B0BVV1BX6R",
    product_photo:
      "https://m.media-amazon.com/images/I/61rw6RkP9JL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$49.49",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09W5GTXC8",
    product_title: "Nike Men&#x27;s Stroke Running Shoe",
    product_price: "$91.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: "29",
    product_url: "https://www.amazon.com/dp/B09W5GTXC8",
    product_photo:
      "https://m.media-amazon.com/images/I/61bB8CYfybL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$91.98",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0BHXVG9Q6",
    product_title:
      "Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Shedron 3044",
    product_price: "$49.49",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.8",
    product_num_ratings: "38",
    product_url: "https://www.amazon.com/dp/B0BHXVG9Q6",
    product_photo:
      "https://m.media-amazon.com/images/I/612maGs6i9L._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$49.49",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09JKPY3FS",
    product_title:
      "Nike Women&#x27;s Air Huarache Run Ultra White/Black 819151-102",
    product_price: "$70.00",
    product_original_price: "$79.00",
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: "2976",
    product_url: "https://www.amazon.com/dp/B09JKPY3FS",
    product_photo:
      "https://m.media-amazon.com/images/I/41qGMkm5wzL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$70.00",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0BH59JBBD",
    product_title:
      "Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Shedron 2167",
    product_price: "$49.49",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4",
    product_num_ratings: "107",
    product_url: "https://www.amazon.com/dp/B0BH59JBBD",
    product_photo:
      "https://m.media-amazon.com/images/I/61zC6cbk9NL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$49.49",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0BSMSDX6G",
    product_title:
      "Mexico en la Piel Leather Huarache Sandals for Womans. Handmade Shoes",
    product_price: "$49.59",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: "7",
    product_url: "https://www.amazon.com/dp/B0BSMSDX6G",
    product_photo:
      "https://m.media-amazon.com/images/I/616vkdvIrFL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$49.59",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B07NFDLSHQ",
    product_title:
      "Sunsteps Barclay Men&#x27;s Hand Woven Leather Huarache Sandal for All-Day Comfort",
    product_price: "$54.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: "712",
    product_url: "https://www.amazon.com/dp/B07NFDLSHQ",
    product_photo:
      "https://m.media-amazon.com/images/I/81WtPvoSFJL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$54.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B098NZZP3R",
    product_title:
      "Nisolo Men&#x27;s Huarache Sandal - Slip-On, Waterproof, Flexible, Breathable and Comfortable Mexican Huaraches For Men, Youth, Boys - Casual and Everyday Mens Woven Leather Sandals",
    product_price: "$150.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: "238",
    product_url: "https://www.amazon.com/dp/B098NZZP3R",
    product_photo:
      "https://m.media-amazon.com/images/I/71wd19bXBdL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$150.00",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B081LLZWCY",
    product_title:
      "Sunsteps Venetian Women&#x27;s Hand Woven Leather Huarache Sandal for All-Day Comfort",
    product_price: "$44.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: "394",
    product_url: "https://www.amazon.com/dp/B081LLZWCY",
    product_photo:
      "https://m.media-amazon.com/images/I/81YhS54sYbL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$44.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09W5GTXC8",
    product_title: "Nike Men&#x27;s Stroke Running Shoe",
    product_price: "$91.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: "29",
    product_url: "https://www.amazon.com/dp/B09W5GTXC8",
    product_photo:
      "https://m.media-amazon.com/images/I/61bB8CYfybL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$91.98",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0BHXVG9Q6",
    product_title:
      "Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Shedron 3044",
    product_price: "$49.49",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.8",
    product_num_ratings: "38",
    product_url: "https://www.amazon.com/dp/B0BHXVG9Q6",
    product_photo:
      "https://m.media-amazon.com/images/I/612Kw6xCRAL Background Removed._AC_SR525,789_QL65_.png",
    product_num_offers: null,
    product_minimum_offer_price: "$49.49",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
];

const costumes_data = [
  {
    asin: "B089VLF9KT",
    product_title:
      "Halloween Spider Costume for Dog Cat, Halloween Pet Costume Halloween Decorations, Spider Decor Halloween Party Supply, Spider Cosplay Costumes with Adjustable Velcro for Small Medium Dogs and Cats",
    product_price: "$8.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.7",
    product_num_ratings: 497,
    product_url: "https://www.amazon.com/dp/B089VLF9KT",
    product_photo:
      "https://m.media-amazon.com/images/I/710SoDYjILS._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$8.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09V753TRH",
    product_title:
      "5 Pieces Pet Cat Halloween Costume Small Dog Vampire Cloak Bat Pumpkin Witch Hat with Adjustable Strap Skeleton Dog Bib Collar with Bells for Cat Halloween Bloody Zombie Party (Simple Style)",
    product_price: "$14.99",
    product_original_price: "$15.99",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 25,
    product_url: "https://www.amazon.com/dp/B09V753TRH",
    product_photo:
      "https://m.media-amazon.com/images/I/71kYrVRmcUL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$14.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09499WPND",
    product_title:
      "T2Y Cowboy Rider Dog Costume - Halloween Dog Costumes for Small Dogs or Cats, Dogs Clothes Knight Style with Doll and Hat for Halloween Day Pet Costume(Small)",
    product_price: "$12.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 371,
    product_url: "https://www.amazon.com/dp/B09499WPND",
    product_photo:
      "https://m.media-amazon.com/images/I/41EakiB0FWL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$12.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0CB2C7RP9",
    product_title:
      "Vellibring Halloween Pet Cape Costume Cat Vampire Cloak Cat Wizard Outfit Pet Witch Cosplay Apparel Halloween Pet Cloak Party Costumes for Small Medium Dogs Cats Supplies",
    product_price: "$9.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: 3,
    product_url: "https://www.amazon.com/dp/B0CB2C7RP9",
    product_photo:
      "https://m.media-amazon.com/images/I/71+ldmQU+YL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$9.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B08BJMD2GR",
    product_title:
      "Dog Cat Spider Costume for Halloween Party Decoration, Halloween Cosplay Costumes for Small Dogs and Cat, Puppy Cat Dress Up Accessories Black",
    product_price: "$7.99",
    product_original_price: "$9.99",
    currency: "USD",
    product_star_rating: "3.6",
    product_num_ratings: 633,
    product_url: "https://www.amazon.com/dp/B08BJMD2GR",
    product_photo:
      "https://m.media-amazon.com/images/I/61PPCI3J62L._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$7.99",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B06XVY9G39",
    product_title:
      "NACOCO Cowboy Dog Costume with Hat Dog Clothes Halloween Costumes for Cat and Small Dog (Medium) Blue",
    product_price: "$13.49",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 1331,
    product_url: "https://www.amazon.com/dp/B06XVY9G39",
    product_photo:
      "https://m.media-amazon.com/images/I/51itKrppI2L._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$13.49",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0B6F5VMX2",
    product_title:
      "Dog Cape Costume - Pet Halloween Costumes Cat Vampire Cloak, Dog Witch Clothes for Small Medium Dogs Cats Puppy, Funny Dog Cosplay Dress Wizard Outfit, Dog Mantle Apparel for Halloween Party",
    product_price: "$12.99",
    product_original_price: "$19.99",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 106,
    product_url: "https://www.amazon.com/dp/B0B6F5VMX2",
    product_photo:
      "https://m.media-amazon.com/images/I/71DSqmlWmTL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$12.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09C66V1SZ",
    product_title:
      "Dxhycc Halloween Pet Costume Cat Wizard Costume Funny Wizard Cat Clothes Cloak and Wizard Hat for Small Dogs Cats Outfits",
    product_price: "$9.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 145,
    product_url: "https://www.amazon.com/dp/B09C66V1SZ",
    product_photo:
      "https://m.media-amazon.com/images/I/71i4gLCjzZL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$9.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09XXHQ7VP",
    product_title:
      "YUJUN Cat Halloween Costume Pets Bat Wing with Pumpkin Shaped Jingle Bells Accessory for Puppy Kitten Halloween Party Costume Supplies",
    product_price: "$6.29",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4",
    product_num_ratings: 100,
    product_url: "https://www.amazon.com/dp/B09XXHQ7VP",
    product_photo:
      "https://m.media-amazon.com/images/I/61EJ00YWeCL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$6.29",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0711H3RB6",
    product_title:
      "Mikayoo Pet Dog Cat Halloween Costumes,The Cowboy for Party Christmas Special Events Costume,West Cowboy Uniform with Hat,Funny Pet Cowboy Outfit Clothing for Dog cat(XS)",
    product_price: "$11.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 1127,
    product_url: "https://www.amazon.com/dp/B0711H3RB6",
    product_photo:
      "https://m.media-amazon.com/images/I/617litpPQoL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$11.98",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0B56C66J2",
    product_title:
      "ITESSY Cat Halloween Costumes- Black Lion Mane Wig Pet Costumes Hat for Halloween Christmas Dress Up Accessories Decoration for Kitten Cats,Size M",
    product_price: "$9.23",
    product_original_price: "$10.99",
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 98,
    product_url: "https://www.amazon.com/dp/B0B56C66J2",
    product_photo:
      "https://m.media-amazon.com/images/I/71qG2vz53qL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$9.23",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B07GFND8ZC",
    product_title:
      "Pet Cat Bat Wings for Halloween Party Decoration, Puppy Collar Leads Cosplay Bat Costume,Cute Puppy Cat Dress Up Accessories",
    product_price: "$5.59",
    product_original_price: "$12.99",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 6867,
    product_url: "https://www.amazon.com/dp/B07GFND8ZC",
    product_photo:
      "https://m.media-amazon.com/images/I/51kh1vgB9aL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$5.59",
    is_best_seller: true,
    is_prime: false,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0BBZVRDTH",
    product_title:
      "Finevalue Cat Dog Noble Halloween Cloak Cool Vampire Suit Cosplay Dress Outfit Small Medium Cat Dog Puppy Devil Costume (JZZ008-1)",
    product_price: "$14.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 34,
    product_url: ",https://www.amazon.com/dp/B0BBZVRDTH",
    product_photo:
      "https://m.media-amazon.com/images/I/61PE9ImtdkL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$14.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B074WP1RT3",
    product_title:
      "ANIAC Pet Pumpkin Costume Cat Halloween Hat Cloak Sets Puppy Poncho Dog Halloween Cosplay for Kitty Small Medium Sized Dog",
    product_price: "$13.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 220,
    product_url: "https://www.amazon.com/dp/B074WP1RT3",
    product_photo:
      "https://m.media-amazon.com/images/I/51kou410CqL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$13.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
];

const customers = [
  {
    name: "Lauren",
    username: "lolomayne",
    password: "password",
    fav_brand: "Nike",
  },
  {
    name: "Bruno",
    username: "bruno",
    password: "iamcool",
    fav_brand: "adidas",
  },
  {
    name: "Winston",
    username: "winston",
    password: "iluvaldi",
    fav_brand: "Converse",
  },
  {
    name: "Alden",
    username: "alden",
    password: "iluvbro",
    fav_brand: "Vans",
  },
];

const closets = [
  {
    creatorId: "bruno",
    name: "Hi-Kickin It: This 'name' field acts as a 'nickname' for the closet, related to the product_type",
    background: "./db/underwater.jpg",
    product_type: { sneaks_data },
    isTemplate: true,
  },
  {
    creatorId: "bruno",
    name: "Big BOO! = costumes for Halloween, currently featuring pet costumes",
    background: "./db/riverfantasy.jpg",
    product_type: { costumes_data },
    isTemplate: true,
  },
  {
    creatorId: "winston",
    name: "oh the places we'll go! including anything from plants to furniture to dresses",
    background: "./db/nikeairneon.png",
    product_type: "variety",
    isTemplate: true,
  },
  {
    creatorId: "bruno",
    name: "'ON ALDEN POND': may include menswear, mens care or beauty, siren suits, suit suits, ties, books, or gadgets",
    background: "./db/flyaway.png",
    product_type: "books, etc.",
    isTemplate: true,
  },
];

module.exports = { sneaks_data, costumes_data, customers, closets };
