const sneaks_data = [
  {
    asin: "B072JGTM91",
    product_title: "adidas unisex-adult Low-top",
    product_price: "$68.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.4,
    product_num_ratings: 551,
    product_url: "https:|//www.amazon.com/dp/B072JGTM91",
    product_photo:
      "https:|//m.media-amazon.com/images/I/51+M+so6FqL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$68.99",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0BG39JVYR",
    product_title: "adidas Unisex-Adult Top Sala Competition Sneaker",
    product_price: "$79.95",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https:|//www.amazon.com/dp/B0BG39JVYR",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71ZX5+QDSdL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$79.95",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B09NGX8PFX",
    product_title: "adidas Originals Men&#x27;s Top Ten Hi Basketball Shoes",
    product_price: "$89.90",
    product_original_price: "$100.00",
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 130,
    product_url: "https:|//www.amazon.com/dp/B09NGX8PFX",
    product_photo:
      "https:|//m.media-amazon.com/images/I/51UskB9u6VL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$89.90",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B091ZDX179",
    product_title: "adidas Unisex-Adult Adilette Slide Sandal",
    product_price: "$29.50",
    product_original_price: "$35.00",
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 9326,
    product_url: "https:|//www.amazon.com/dp/B091ZDX179",
    product_photo:
      "https:|//m.media-amazon.com/images/I/61ncshdbtdL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$29.50",
    is_best_seller: TRUE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B091V59R4Y",
    product_title: "adidas Men&#x27;s Top Ten Red Bulls Sneaker",
    product_price: "$62.37",
    product_original_price: "$100.00",
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 507,
    product_url: "https:|//www.amazon.com/dp/B091V59R4Y",
    product_photo:
      "https:|//m.media-amazon.com/images/I/710vaoYMEhL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$62.37",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0BN2DGD1C",
    product_title: "adidas Unisex-Adult D.O.N. Issue 3 Basketball Shoe",
    product_price: "$62.67",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.5,
    product_num_ratings: 923,
    product_url: "https:|//www.amazon.com/dp/B0BN2DGD1C",
    product_photo:
      "https:|//m.media-amazon.com/images/I/31huIGQnqZL._AC_SR500,752_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$62.67",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B09VCNQZ2W",
    product_title: "adidas Unisex Soccer Shoe",
    product_price: "$68.00",
    product_original_price: "$90.00",
    currency: "USD",
    product_star_rating: 3.9,
    product_num_ratings: 208,
    product_url: "https:|//www.amazon.com/dp/B09VCNQZ2W",
    product_photo:
      "https:|//m.media-amazon.com/images/I/61CidG-n-ML._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$68.00",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
    sales_volume: null,
  },
  {
    asin: "B07ZHX299V",
    product_title: "adidas Originals Men&#x27;s Top Ten Sneaker",
    product_price: "$89.90",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.7,
    product_num_ratings: 600,
    product_url: "https:|//www.amazon.com/dp/B07ZHX299V",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71azslUzEEL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$89.90",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B09VCP36MW",
    product_title: "adidas Unisex-Adult Copa Pure.3 Firm GroundSneaker",
    product_price: "$85.05",
    product_original_price: "$130.00",
    currency: "USD",
    product_star_rating: 4.1,
    product_num_ratings: 23,
    product_url: "https:|//www.amazon.com/dp/B09VCP36MW",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71jTyollFAL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$85.05",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B09Y743BHX",
    product_title: "adidas Unisex-Adult Copa Pure.3 Turf Soccer Shoe",
    product_price: "$67.99",
    product_original_price: "$80.00",
    currency: "USD",
    product_star_rating: 3.9,
    product_num_ratings: 50,
    product_url: "https:|//www.amazon.com/dp/B09Y743BHX",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71kYTgFzItL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$67.99",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0BHPS369Q",
    product_title: "adidas Unisex-Adult Dropset 2 Sneaker",
    product_price: "$89.45",
    product_original_price: "$130.00",
    currency: "USD",
    product_star_rating: 4.4,
    product_num_ratings: 4,
    product_url: "https:|//www.amazon.com/dp/B0BHPS369Q",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71PG2I2ZwAL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$89.45",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0B5YL46H5",
    product_title: "adidas Unisex-Adult Sneaker",
    product_price: "$79.94",
    product_original_price: "$100.00",
    currency: "USD",
    product_star_rating: 4.2,
    product_num_ratings: 76,
    product_url: "https:|//www.amazon.com/dp/B0B5YL46H5",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71cCtymGDML._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$79.94",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B09X7DFK5X",
    product_title: "adidas Originals Men&#x27;s Top Ten Rb Sneaker",
    product_price: "$159.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 5,
    product_num_ratings: 1,
    product_url: "https:|//www.amazon.com/dp/B09X7DFK5X",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71BfDn02KGL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$159.00",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B07GR5G7CS",
    product_title: "PUMA Unisex-Adult Rebound Layup Sneaker",
    product_price: "$42.00",
    product_original_price: "$65.00",
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 2816,
    product_url: "https:|//www.amazon.com/dp/B07GR5G7CS",
    product_photo:
      "https:|//m.media-amazon.com/images/I/61xMnRnZVYL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$42.00",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B087FDKSBR",
    product_title: "adidas Unisex-Adult D.o.n. Issue 2 Indoor Court Shoe",
    product_price: "$59.99",
    product_original_price: "$110.00",
    currency: "USD",
    product_star_rating: 4.3,
    product_num_ratings: 1201,
    product_url: "https:|//www.amazon.com/dp/B087FDKSBR",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71aWhzck+AL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$59.99",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B09F92VFTS",
    product_title: "adidas Unisex-Adult Harden Stepback 3 Basketball Shoe",
    product_price: "$65.06",
    product_original_price: "$95.00",
    currency: "USD",
    product_star_rating: 4.4,
    product_num_ratings: 517,
    product_url: "https:|//www.amazon.com/dp/B09F92VFTS",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71iNklWcvSL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$65.06",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B091Z94FLX",
    product_title: "adidas Unisex-Adult Pro N3xt 2021 Basketball Shoe",
    product_price: "$52.66",
    product_original_price: "$70.00",
    currency: "USD",
    product_star_rating: 4.1,
    product_num_ratings: 97,
    product_url: "https:|//www.amazon.com/dp/B091Z94FLX",
    product_photo:
      "https:|//m.media-amazon.com/images/I/6176guV4aVL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$52.66",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B07SDV193X",
    product_title: "adidas Unisex-Adult Adissage Sandal",
    product_price: "$25.59",
    product_original_price: "$32.00",
    currency: "USD",
    product_star_rating: 4.4,
    product_num_ratings: 28195,
    product_url: "https:|//www.amazon.com/dp/B07SDV193X",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71vjxwm9UeL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$25.59",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B08MJN5QFW",
    product_title: "adidas Originals Unisex-Adult Forum MID Sneaker",
    product_price: "$74.96",
    product_original_price: "$110.00",
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 1887,
    product_url: "https:|//www.amazon.com/dp/B08MJN5QFW",
    product_photo:
      "https:|//m.media-amazon.com/images/I/718eAchlkkS._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$74.96",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B09KMLJQV9",
    product_title: "adidas Unisex-Adult D.o.n. Issue 4 Basketball Shoe",
    product_price: "$62.82",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.3,
    product_num_ratings: 162,
    product_url: "https:|//www.amazon.com/dp/B09KMLJQV9",
    product_photo:
      "https:|//m.media-amazon.com/images/I/717aRZH-fDL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$62.82",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0BNJMQJH4",
    product_title: "Nike Unisex-Adult Sneaker",
    product_price: "$74.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 3.7,
    product_num_ratings: 6,
    product_url: "https:|//www.amazon.com/dp/B0BNJMQJH4",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71QZvID5XPL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$74.99",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0BBMQL9HN",
    product_title:
      "Nike Sb Zoom Blazer Mid PRM Mens Trainers Da1839 Sneakers Shoes",
    product_price: "$98.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.7,
    product_num_ratings: 99,
    product_url: "https:|//www.amazon.com/dp/B0BBMQL9HN",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71hgGpLd9jL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$98.00",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B07GR5G7CS",
    product_title: "PUMA Unisex-Adult Rebound Layup Sneaker",
    product_price: "$42.00",
    product_original_price: "$65.00",
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 2816,
    product_url: "https:|//www.amazon.com/dp/B07GR5G7CS",
    product_photo:
      "https:|//m.media-amazon.com/images/I/61xMnRnZVYL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$42.00",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B08B3LFQGH",
    product_title: "Nike Unisex-Adult Training Gymnastics Shoe",
    product_price: "$199.95",
    product_original_price: "$229.99",
    currency: "USD",
    product_star_rating: 4.5,
    product_num_ratings: 103,
    product_url: "https:|//www.amazon.com/dp/B08B3LFQGH",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71maGTaBkwL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$199.95",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B07T7HZZKJ",
    product_title: "Nike Air Men&#x27;s Shoes For Men",
    product_price: "$89.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.4,
    product_num_ratings: 20415,
    product_url: "https:|//www.amazon.com/dp/B07T7HZZKJ",
    product_photo:
      "https:|//m.media-amazon.com/images/I/61cE4FW44WL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$89.99",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0C2F9TVQC",
    product_title: "Nike Women&#x27;s Gymnastics Shoes",
    product_price: "$147.84",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.5,
    product_num_ratings: 1461,
    product_url: "https:|//www.amazon.com/dp/B0C2F9TVQC",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71dMpU2YpCL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$147.84",
    is_best_seller: TRUE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B091ZDX179",
    product_title: "adidas Unisex-Adult Adilette Slide Sandal",
    product_price: "$29.50",
    product_original_price: "$35.00",
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 9326,
    product_url: "https:|//www.amazon.com/dp/B091ZDX179",
    product_photo:
      "https:|//m.media-amazon.com/images/I/61ncshdbtdL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$29.50",
    is_best_seller: TRUE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0C15S1QPH",
    product_title: "Nike Women&#x27;s Basketball Shoe",
    product_price: "$190.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 1802,
    product_url: "https:|//www.amazon.com/dp/B0C15S1QPH",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71GaNqL9XkL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$190.00",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0C5Z7RQ1Z",
    product_title: "Nike Men&#x27;s Sneakers",
    product_price: "$102.97",
    product_original_price: "$108.08",
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 590,
    product_url: "https:|//www.amazon.com/dp/B0C5Z7RQ1Z",
    product_photo:
      "https:|//m.media-amazon.com/images/I/5187TK3XLcL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$102.97",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0C54L777B",
    product_title: "Nike Men&#x27;s Low-Top Sneakers",
    product_price: "$89.93",
    product_original_price: "$99.95",
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 2698,
    product_url: "https:|//www.amazon.com/dp/B0C54L777B",
    product_photo:
      "https:|//m.media-amazon.com/images/I/714AI9hq3WL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$89.93",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B09M7FCDS3",
    product_title: "Nike Men&#x27;s Basketball",
    product_price: "$135.15",
    product_original_price: "$145.00",
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 663,
    product_url: "https:|//www.amazon.com/dp/B09M7FCDS3",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71OLGr4D9IL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$135.15",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0BRPLM75S",
    product_title: "Nike Jordan Unisex-Adult Basketball Shoes",
    product_price: "$129.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.5,
    product_num_ratings: 229,
    product_url: "https:|//www.amazon.com/dp/B0BRPLM75S",
    product_photo:
      "https:|//m.media-amazon.com/images/I/718O6FXpU8L._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$129.98",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B093TSRMG6",
    product_title: "Reebok Unisex Classic Leather Sneaker",
    product_price: "$79.37",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 18676,
    product_url: "https:|//www.amazon.com/dp/B093TSRMG6",
    product_photo:
      "https:|//m.media-amazon.com/images/I/41p7zTWIBsL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$79.37",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B005UA2MPQ",
    product_title: "Nike Basketball Shoe",
    product_price: "$135.00",
    product_original_price: "$189.99",
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 7316,
    product_url: "https:|//www.amazon.com/dp/B005UA2MPQ",
    product_photo:
      "https:|//m.media-amazon.com/images/I/81zN34Whk2L._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$135.00",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0C1L2RZZZ",
    product_title: "Nike Unisex Air Zoom G.T. Cut 2 Basketball Shoe",
    product_price: "$159.86",
    product_original_price: "$208.00",
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https:|//www.amazon.com/dp/B0C1L2RZZZ",
    product_photo:
      "https:|//m.media-amazon.com/images/I/61qwtLpMU6L._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$159.86",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0B51SWNRH",
    product_title: "Nike Men&#x27;s Football Shoe",
    product_price: "$123.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.1,
    product_num_ratings: 29,
    product_url: "https:|//www.amazon.com/dp/B0B51SWNRH",
    product_photo:
      "https:|//m.media-amazon.com/images/I/61Xos+V3eKL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$123.00",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B07R2WX8XX",
    product_title: "Nike Basketball Shoe",
    product_price: "$88.99",
    product_original_price: "$99.00",
    currency: "USD",
    product_star_rating: 4.5,
    product_num_ratings: 2751,
    product_url: "https:|//www.amazon.com/dp/B07R2WX8XX",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71aw2Z+2WML._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$88.99",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B083FRDJZ1",
    product_title: "Nike Women&#x27;s Gymnastics Shoe",
    product_price: "$99.99",
    product_original_price: "$119.99",
    currency: "USD",
    product_star_rating: 4.4,
    product_num_ratings: 1019,
    product_url: "https:|//www.amazon.com/dp/B083FRDJZ1",
    product_photo:
      "https:|//m.media-amazon.com/images/I/51XTeb2VLSL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$99.99",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0C2T66SJ7",
    product_title:
      "ASoftLand Soccer Cleats Mens Women Football Cleats for Big Boy AG/FG",
    product_price: "$31.48",
    product_original_price: "$37.59",
    currency: "USD",
    product_star_rating: 4.2,
    product_num_ratings: 112,
    product_url: "https:|//www.amazon.com/dp/B0C2T66SJ7",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71r0FClSaCL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$31.48",
    is_best_seller: TRUE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B000UYJBQA",
    product_title: "Vans Unisex-Child Old Skool V Core (Toddler)",
    product_price: "$59.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.6,
    product_num_ratings: 31780,
    product_url: "https:|//www.amazon.com/dp/B000UYJBQA",
    product_photo:
      "https:|//m.media-amazon.com/images/I/71+uB+EZzDL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$59.00",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
];

const costumes_data = [
  {
    asin: "B00IMB2520",
    product_title:
      "Rubie's Mens It the Movie Pennywise Deluxe Adult Sized Costumes, Yellow",
    product_price: "$51.97",
    product_original_price: "$90.00",
    currency: "USD",
    product_star_rating: 3.9,
    product_num_ratings: 864,
    product_url: "https://www.amazon.com/dp/B00IMB2520",
    product_photo:
      "https://m.media-amazon.com/images/I/71zZskKfPUL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$51.97",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B000VO7792",
    product_title: "Rubie's Costume Cool Ghoul Costume",
    product_price: "$27.29",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 3.7,
    product_num_ratings: 123,
    product_url: "https://www.amazon.com/dp/B000VO7792",
    product_photo:
      "https://m.media-amazon.com/images/I/71kjAruAoGL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$27.29",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B006MRNKFW",
    product_title:
      "Rubie's Batman: The Dark Knight Trilogy Adult Batman Costume",
    product_price: "$45.32",
    product_original_price: "$84.00",
    currency: "USD",
    product_star_rating: 3.9,
    product_num_ratings: 3879,
    product_url: "https://www.amazon.com/dp/B006MRNKFW",
    product_photo:
      "https://m.media-amazon.com/images/I/512IJ7Y0GWL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$45.32",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B00505DVGK",
    product_title: "Rubie's DC Comics Super-Girl T-Shirt With Cape Costume",
    product_price: "$20.27",
    product_original_price: "$36.00",
    currency: "USD",
    product_star_rating: 4.3,
    product_num_ratings: 2924,
    product_url: "https://www.amazon.com/dp/B00505DVGK",
    product_photo:
      "https://m.media-amazon.com/images/I/61wg6z4C17L._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$20.27",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B008M63416",
    product_title: "Rubie's Costume Inflatable Full Body Suit Costume",
    product_price: "$27.93",
    product_original_price: "$68.00",
    currency: "USD",
    product_star_rating: 4.4,
    product_num_ratings: 2066,
    product_url: "https://www.amazon.com/dp/B008M63416",
    product_photo:
      "https://m.media-amazon.com/images/I/715FBK8FFPL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$27.93",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B00505DX22",
    product_title:
      "Rubie's Costume DC Comics Women's Robin T-Shirt With Cape And Eye Mask",
    product_price: "$20.27",
    product_original_price: "$36.00",
    currency: "USD",
    product_star_rating: 4.1,
    product_num_ratings: 1711,
    product_url: "https://www.amazon.com/dp/B00505DX22",
    product_photo:
      "https://m.media-amazon.com/images/I/71q1y5wxkQL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$20.27",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B003D7ZJUI",
    product_title: "Rubie's Beetlejuice Adult Costume",
    product_price: "$34.46",
    product_original_price: "$38.88",
    currency: "USD",
    product_star_rating: 4.1,
    product_num_ratings: 1560,
    product_url: "https://www.amazon.com/dp/B003D7ZJUI",
    product_photo:
      "https://m.media-amazon.com/images/I/712yhPgulKL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$34.46",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B00BLMRHL6",
    product_title:
      "Rubie's Costume Wizard Of Oz 75th Anniversary Edition Adult Scarecrow Costume",
    product_price: "$42.04",
    product_original_price: "$52.99",
    currency: "USD",
    product_star_rating: 4.3,
    product_num_ratings: 758,
    product_url: "https://www.amazon.com/dp/B00BLMRHL6",
    product_photo:
      "https://m.media-amazon.com/images/I/71IYbg-ci3L._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$42.04",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B008TNNLTW",
    product_title:
      "Rubie's Costume Heroes And Hombres Men's Hippie Shirt And Wig",
    product_price: "$23.72",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.2,
    product_num_ratings: 1116,
    product_url: "https://www.amazon.com/dp/B008TNNLTW",
    product_photo:
      "https://m.media-amazon.com/images/I/71uf30cOCaL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$23.72",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B0087JGF00",
    product_title:
      "Rubie's Costume Heroes And Hombres Adult Police Officer Shirt And Hat",
    product_price: "$20.71",
    product_original_price: "$29.99",
    currency: "USD",
    product_star_rating: 4,
    product_num_ratings: 501,
    product_url: "https://www.amazon.com/dp/B0087JGF00",
    product_photo:
      "https://m.media-amazon.com/images/I/713fcp1iH0L._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$20.71",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B00505DW0A",
    product_title: "Rubie's DC Comics Batgirl T-Shirt with Cape and Mask",
    product_price: "$21.75",
    product_original_price: "$32.99",
    currency: "USD",
    product_star_rating: 4.3,
    product_num_ratings: 2314,
    product_url: "https://www.amazon.com/dp/B00505DW0A",
    product_photo:
      "https://m.media-amazon.com/images/I/71t8-rtAbbL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$21.75",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B07CLMCC91",
    product_title:
      "Rubie's Men's Standard Movie Adult Aquaman Deluxe Costume, As Shown",
    product_price: "$51.80",
    product_original_price: "$61.99",
    currency: "USD",
    product_star_rating: 4.1,
    product_num_ratings: 538,
    product_url: "https://www.amazon.com/dp/B07CLMCC91",
    product_photo:
      "https://m.media-amazon.com/images/I/81RL7jF2xrL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$51.80",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B01C5CSGEM",
    product_title: "Rubie's Costume Women's Supergirl Tv Show Costume Dress",
    product_price: "$39.74",
    product_original_price: "$59.99",
    currency: "USD",
    product_star_rating: 4.5,
    product_num_ratings: 2107,
    product_url: "https://www.amazon.com/dp/B01C5CSGEM",
    product_photo:
      "https://m.media-amazon.com/images/I/71R0VJ9ni9L._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$39.74",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B00C0PF9JA",
    product_title:
      "Rubie's Costume Grand Heritage Catwoman Classic TV Batman Circa 1966 Costume",
    product_price: "$129.30",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.4,
    product_num_ratings: 361,
    product_url: "https://www.amazon.com/dp/B00C0PF9JA",
    product_photo:
      "https://m.media-amazon.com/images/I/71t-cyXxlFL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$129.30",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B003Y3KB4U",
    product_title: "Rubie's Costume Haunted House Collection Caveman Costume",
    product_price: "$17.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 3.9,
    product_num_ratings: 223,
    product_url: "https://www.amazon.com/dp/B003Y3KB4U",
    product_photo:
      "https://m.media-amazon.com/images/I/81Wa1nXnYNL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$17.99",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B07NWMZLM5",
    product_title: "Rubie's IT Movie Women's Deluxe Pennywise Costume",
    product_price: "$48.74",
    product_original_price: "$59.99",
    currency: "USD",
    product_star_rating: 4.2,
    product_num_ratings: 527,
    product_url: "https://www.amazon.com/dp/B07NWMZLM5",
    product_photo:
      "https://m.media-amazon.com/images/I/81h329dQuiL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$48.74",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B00UI3CDE0",
    product_title: "Rubie's Costume Co Men's Inflatable Evil Clown Costume",
    product_price: "$69.99",
    product_original_price: "$75.00",
    currency: "USD",
    product_star_rating: 4.4,
    product_num_ratings: 217,
    product_url: "https://www.amazon.com/dp/B00UI3CDE0",
    product_photo:
      "https://m.media-amazon.com/images/I/81uBuT+xHBL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$69.99",
    is_best_seller: FALSE,
    is_prime: FALSE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B002QE7KBU",
    product_title: "Rubie's Elvis Now Deluxe Aloha Elvis Costume",
    product_price: "$47.19",
    product_original_price: null,
    currency: "USD",
    product_star_rating: 4.3,
    product_num_ratings: 1238,
    product_url: "https://www.amazon.com/dp/B002QE7KBU",
    product_photo:
      "https://m.media-amazon.com/images/I/71s9MApCJNL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$47.19",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B000HVO28I",
    product_title: "Rubie's Scooby-Doo Deluxe Adult Costume",
    product_price: "$18.06",
    product_original_price: "$35.00",
    currency: "USD",
    product_star_rating: 3.5,
    product_num_ratings: 1422,
    product_url: "https://www.amazon.com/dp/B000HVO28I",
    product_photo:
      "https://m.media-amazon.com/images/I/71GKoozC-VL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$18.06",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },
  {
    asin: "B06XRB57WF",
    product_title: "Rubie's Velociraptor Inflatable Adult Costume",
    product_price: "$61.85",
    product_original_price: "$89.99",
    currency: "USD",
    product_star_rating: 4.1,
    product_num_ratings: 1136,
    product_url: "https://www.amazon.com/dp/B06XRB57WF",
    product_photo:
      "https://m.media-amazon.com/images/I/71aYFNkflkL._AC_SR525,789_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$61.85",
    is_best_seller: FALSE,
    is_prime: TRUE,
    climate_pledge_friendly: FALSE,
  },

  {
    asin: "B09499WPND",
    product_title:
      "T2Y Cowboy Rider Dog Costume - Halloween Dog Costumes for Small Dogs or Cats, Dogs Clothes Knight Style with Doll and Hat for Halloween Day Pet Costume(Small)",
    product_price: "$12.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 371,
    product_url: "https://www.amazon.com/dp/B09499WPND",
    product_photo:
      "https://m.media-amazon.com/images/I/41EakiB0FWL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$12.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0CB2C7RP9",
    product_title:
      "Vellibring Halloween Pet Cape Costume Cat Vampire Cloak Cat Wizard Outfit Pet Witch Cosplay Apparel Halloween Pet Cloak Party Costumes for Small Medium Dogs Cats Supplies",
    product_price: "$9.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: 3,
    product_url: "https://www.amazon.com/dp/B0CB2C7RP9",
    product_photo:
      "https://m.media-amazon.com/images/I/71+ldmQU+YL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$9.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },

  {
    asin: "B06XVY9G39",
    product_title:
      "NACOCO Cowboy Dog Costume with Hat Dog Clothes Halloween Costumes for Cat and Small Dog (Medium) Blue",
    product_price: "$13.49",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 1331,
    product_url: "https://www.amazon.com/dp/B06XVY9G39",
    product_photo:
      "https://m.media-amazon.com/images/I/51itKrppI2L._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$13.49",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0B6F5VMX2",
    product_title:
      "Dog Cape Costume - Pet Halloween Costumes Cat Vampire Cloak, Dog Witch Clothes for Small Medium Dogs Cats Puppy, Funny Dog Cosplay Dress Wizard Outfit, Dog Mantle Apparel for Halloween Party",
    product_price: "$12.99",
    product_original_price: "$19.99",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 106,
    product_url: "https://www.amazon.com/dp/B0B6F5VMX2",
    product_photo:
      "https://m.media-amazon.com/images/I/71DSqmlWmTL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$12.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09C66V1SZ",
    product_title:
      "Dxhycc Halloween Pet Costume Cat Wizard Costume Funny Wizard Cat Clothes Cloak and Wizard Hat for Small Dogs Cats Outfits",
    product_price: "$9.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 145,
    product_url: "https://www.amazon.com/dp/B09C66V1SZ",
    product_photo:
      "https://m.media-amazon.com/images/I/71i4gLCjzZL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$9.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B09XXHQ7VP",
    product_title:
      "YUJUN Cat Halloween Costume Pets Bat Wing with Pumpkin Shaped Jingle Bells Accessory for Puppy Kitten Halloween Party Costume Supplies",
    product_price: "$6.29",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4",
    product_num_ratings: 100,
    product_url: "https://www.amazon.com/dp/B09XXHQ7VP",
    product_photo:
      "https://m.media-amazon.com/images/I/61EJ00YWeCL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$6.29",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0711H3RB6",
    product_title:
      "Mikayoo Pet Dog Cat Halloween Costumes,The Cowboy for Party Christmas Special Events Costume,West Cowboy Uniform with Hat,Funny Pet Cowboy Outfit Clothing for Dog cat(XS)",
    product_price: "$11.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 1127,
    product_url: "https://www.amazon.com/dp/B0711H3RB6",
    product_photo:
      "https://m.media-amazon.com/images/I/617litpPQoL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$11.98",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B0B56C66J2",
    product_title:
      "ITESSY Cat Halloween Costumes- Black Lion Mane Wig Pet Costumes Hat for Halloween Christmas Dress Up Accessories Decoration for Kitten Cats,Size M",
    product_price: "$9.23",
    product_original_price: "$10.99",
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 98,
    product_url: "https://www.amazon.com/dp/B0B56C66J2",
    product_photo:
      "https://m.media-amazon.com/images/I/71qG2vz53qL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$9.23",
    is_best_seller: false,
    is_prime: false,
    climate_pledge_friendly: false,
  },

  {
    asin: "B0BBZVRDTH",
    product_title:
      "Finevalue Cat Dog Noble Halloween Cloak Cool Vampire Suit Cosplay Dress Outfit Small Medium Cat Dog Puppy Devil Costume (JZZ008-1)",
    product_price: "$14.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 34,
    product_url: ",https://www.amazon.com/dp/B0BBZVRDTH",
    product_photo:
      "https://m.media-amazon.com/images/I/61PE9ImtdkL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$14.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
  {
    asin: "B074WP1RT3",
    product_title:
      "ANIAC Pet Pumpkin Costume Cat Halloween Hat Cloak Sets Puppy Poncho Dog Halloween Cosplay for Kitty Small Medium Sized Dog",
    product_price: "$13.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 220,
    product_url: "https://www.amazon.com/dp/B074WP1RT3",
    product_photo:
      "https://m.media-amazon.com/images/I/51kou410CqL._AC_SX444_SY639_QL65_.jpg",
    product_num_offers: null,
    product_minimum_offer_price: "$13.99",
    is_best_seller: false,
    is_prime: true,
    climate_pledge_friendly: false,
  },
];

const customers = [
  {
    name: "Lauren",
    username: "lolomayne",
    password: "password",
    fav_brand: "Nike",
  },
  {
    name: "Bruno",
    username: "bruno",
    password: "iamcool",
    fav_brand: "adidas",
  },
  {
    name: "Winston",
    username: "winston",
    password: "iluvaldi",
    fav_brand: "Converse",
  },
  {
    name: "Alden",
    username: "alden",
    password: "iluvbro",
    fav_brand: "Vans",
  },
];

const closets = [
  {
    creator_id: "bruno",
    name: "High-Kickin It",
    background: "./db/underwater.jpg",
    product_type: "sneakers",
    isTemplate: true,
  },
  {
    creator_id: "bruno",
    name: "Big BOO!",
    background: "./db/riverfantasy.jpg",
    product_type: "costumes",
    isTemplate: true,
  },
  {
    creator_id: "winston",
    name: "oh the places we'll go!",
    background: "./db/nikeairneon.png",
    product_type: "variety",
    isTemplate: true,
  },
  {
    creator_id: "bruno",
    name: "'ON ALDEN POND",
    background: "./db/flyaway.png",
    product_type: "books, etc.",
    isTemplate: true,
  },
];

module.exports = { sneaks_data, costumes_data, customers, closets };
