sneaks_data = [
	
	{
	  asin: "B09KDLZDKW",
	  product_title: "Nike Air Huarache, Men&#x27;s Running Shoes",
	  product_price: "$99.99",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4.1",
	  product_num_ratings: 12,
	  product_url: "https://www.amazon.com/dp/B09KDLZDKW",
	  product_photo:
		"https://m.media-amazon.com/images/I/51uBjPAKjeL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$99.99",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B09JKPY3FS",
	  product_title:
		"Nike Women&#x27;s Air Huarache Run Ultra White/Black 819151-102",
	  product_price: "$70.00",
	  product_original_price: "$79.00",
	  currency: "USD",
	  product_star_rating: "4.1",
	  product_num_ratings: 2976,
	  product_url: "https://www.amazon.com/dp/B09JKPY3FS",
	  product_photo:
		"https://m.media-amazon.com/images/I/41qGMkm5wzL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$70.00",
	  is_best_seller: false,
	  is_prime: false,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B0B5B5DFHB",
	  product_title: "Nike Air Huarache Se Womens",
	  product_price: "$86.99",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4",
	  product_num_ratings: 5,
	  product_url: "https://www.amazon.com/dp/B0B5B5DFHB",
	  product_photo:
		"https://m.media-amazon.com/images/I/6193wZ0x-JL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$86.99",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B099Q1Z1SR",
	  product_title: "Nike Unisex-Child Free Rn (Big Kid) Running Shoes, 6.5 US",
	  product_price: "$73.90",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4.6",
	  product_num_ratings: 5220,
	  product_url: "https://www.amazon.com/dp/B099Q1Z1SR",
	  product_photo:
		"https://m.media-amazon.com/images/I/41uiBby-JqL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$73.90",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B0BH59JBBD",
	  product_title:
		"Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Shedron 2167",
	  product_price: "$49.49",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4",
	  product_num_ratings: 107,
	  product_url: "https://www.amazon.com/dp/B0BH59JBBD",
	  product_photo:
		"https://m.media-amazon.com/images/I/61zC6cbk9NL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$49.49",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B09J3J72Q3",
	  product_title:
		"Nike Men&#x27;s Air Huarache Fashion Sneakers, Black/Black, 7.5",
	  product_price: "$89.99",
	  product_original_price: "$109.96",
	  currency: "USD",
	  product_star_rating: "4.5",
	  product_num_ratings: 8,
	  product_url: "https://www.amazon.com/dp/B09J3J72Q3",
	  product_photo:
		"https://m.media-amazon.com/images/I/51+z7E8P3hL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$89.99",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B0BHXXN5G7",
	  product_title:
		"Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Tan 4150",
	  product_price: "$49.49",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4.3",
	  product_num_ratings: 70,
	  product_url: "https://www.amazon.com/dp/B0BHXXN5G7",
	  product_photo:
		"https://m.media-amazon.com/images/I/612maGs6i9L._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$49.49",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B0BSMSDX6G",
	  product_title:
		"Mexico en la Piel Leather Huarache Sandals for Womans. Handmade Shoes",
	  product_price: "$49.59",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "5",
	  product_num_ratings: 7,
	  product_url: "https://www.amazon.com/dp/B0BSMSDX6G",
	  product_photo:
		"https://m.media-amazon.com/images/I/616vkdvIrFL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$49.59",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B07NFDLSHQ",
	  product_title:
		"Sunsteps Barclay Men&#x27;s Hand Woven Leather Huarache Sandal for All-Day Comfort",
	  product_price: "$54.99",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4.4",
	  product_num_ratings: 712,
	  product_url: "https://www.amazon.com/dp/B07NFDLSHQ",
	  product_photo:
		"https://m.media-amazon.com/images/I/81WtPvoSFJL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$54.99",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B06Y22QF81",
	  product_title: "Deer Stags Men&#x27;s Huarache Sandal",
	  product_price: "$54.99",
	  product_original_price: "$85.00",
	  currency: "USD",
	  product_star_rating: "4.4",
	  product_num_ratings: 2649,
	  product_url: "https://www.amazon.com/dp/B06Y22QF81",
	  product_photo:
		"https://m.media-amazon.com/images/I/71sDktg4sjL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$54.99",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B098NZZP3R",
	  product_title:
		"Nisolo Men&#x27;s Huarache Sandal - Slip-On, Waterproof, Flexible, Breathable and Comfortable Mexican Huaraches For Men, Youth, Boys - Casual and Everyday Mens Woven Leather Sandals",
	  product_price: "$150.00",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4.2",
	  product_num_ratings: 238,
	  product_url: "https://www.amazon.com/dp/B098NZZP3R",
	  product_photo:
		"https://m.media-amazon.com/images/I/71wd19bXBdL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$150.00",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B0BZ3YNYSY",
	  product_title:
		"Mexico en la Piel Leather Lace Up Huarache Sandals for Woman. Chiselled Flowers",
	  product_price: "$49.59",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "3.7",
	  product_num_ratings: 17,
	  product_url: "https://www.amazon.com/dp/B0BZ3YNYSY",
	  product_photo:
		"https://m.media-amazon.com/images/I/51GOvCheZDL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$49.59",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B0BVF1SNSP",
	  product_title:
		"Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Shedron 911 Ankle Strap",
	  product_price: "$49.49",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4.6",
	  product_num_ratings: 28,
	  product_url: "https://www.amazon.com/dp/B0BVF1SNSP",
	  product_photo:
		"https://m.media-amazon.com/images/I/61H9df1FC7L._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$49.49",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B0BZCJ3R31",
	  product_title:
		"Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Shedron Erica",
	  product_price: "$49.49",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4.1",
	  product_num_ratings: 14,
	  product_url: "https://www.amazon.com/dp/B0BZCJ3R31",
	  product_photo:
		"https://m.media-amazon.com/images/I/61yqN2pLFCL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$49.49",
	  is_best_seller: false,
	  is_prime: false,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B08FXT1TGW",
	  product_title:
		"Generic The Western Shops Mens Leather Sandals Mens Mexican Huarache Sandal",
	  product_price: "$39.99",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4",
	  product_num_ratings: 143,
	  product_url: "https://www.amazon.com/dp/B08FXT1TGW",
	  product_photo:
		"https://m.media-amazon.com/images/I/71RDLRP0UOL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$39.99",
	  is_best_seller: false,
	  is_prime: false,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B09H688BWP",
	  product_title:
		"Generic Western Shops Womens Leather Mexican Huarache Sandal, Womens Huarache Leather Wedge Sandal",
	  product_price: "$48.95",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4.3",
	  product_num_ratings: 154,
	  product_url: "https://www.amazon.com/dp/B09H688BWP",
	  product_photo:
		"https://m.media-amazon.com/images/I/71LOgkJEWZL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$48.95",
	  is_best_seller: false,
	  is_prime: false,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B081LLZWCY",
	  product_title:
		"Sunsteps Venetian Women&#x27;s Hand Woven Leather Huarache Sandal for All-Day Comfort",
	  product_price: "$44.99",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4.2",
	  product_num_ratings: 394,
	  product_url: "https://www.amazon.com/dp/B081LLZWCY",
	  product_photo:
		"https://m.media-amazon.com/images/I/81YhS54sYbL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$44.99",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B0BVV1BX6R",
	  product_title:
		"Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Tan 3050 Ankle Strap",
	  product_price: "$49.49",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4.4",
	  product_num_ratings: 4,
	  product_url: "https://www.amazon.com/dp/B0BVV1BX6R",
	  product_photo:
		"https://m.media-amazon.com/images/I/61rw6RkP9JL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$49.49",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B09W5GTXC8",
	  product_title: "Nike Men&#x27;s Stroke Running Shoe",
	  product_price: "$91.98",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "4.2",
	  product_num_ratings: 29,
	  product_url: "https://www.amazon.com/dp/B09W5GTXC8",
	  product_photo:
		"https://m.media-amazon.com/images/I/61bB8CYfybL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$91.98",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
	{
	  asin: "B0BHXVG9Q6",
	  product_title:
		"Macarena Collection Sandals women Huarache Sandal Colorful Leather Mexican Style Color Shedron 3044",
	  product_price: "$49.49",
	  product_original_price: null,
	  currency: "USD",
	  product_star_rating: "3.8",
	  product_num_ratings: 38,
	  product_url: "https://www.amazon.com/dp/B0BHXVG9Q6",
	  product_photo:
		"https://m.media-amazon.com/images/I/612Kw6xCRAL._AC_SR525,789_QL65_.jpg",
	  product_num_offers: null,
	  product_minimum_offer_price: "$49.49",
	  is_best_seller: false,
	  is_prime: true,
	  climate_pledge_friendly: false,
	},
  ];
  


const users = [
	{
	  name: "Lauren",
	  username: "lolomayne",
	  password: "password",
	  fav_pokemon: "Alcremie",
	},
	{
	  name: "Bruno",
	  username: "bruno",
	  password: "iamcool",
	  fav_pokemon: "Lillipup",
	},
	{
	  name: "Winston",
	  username: "winston",
	  password: "iluvpoke",
	  fav_pokemon: "Gengar",
	},
	{
	  name: "Alden",
	  username: "alden",
	  password: "iluvbro",
	  fav_pokemon: "Minun",
	},
	
  ];